name: Try GitAction RunTest

on:
  push:

jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Run Test
        id: runtest
        uses: bo-wang/RunTest-Action@test
        with:
          tag: "Localization"
      - run: "echo token: ${{ steps.runtest.outputs.results-path }}"
